### ISSUE TITLE
SUGGEST CHANGES HERE !

### ISSUE THREAD

**Issue by sudhanshutiwari264** [sudhanshutiwari264/Making-class-in-different-Programming-languages-#19]
If you wants to add some more topic, do let me know!

**Comment by maanpatel2492** [comment]
> IF YOU WANTS TO ADD SOMETHING MORE , LET ME KNOW!
what exactly the issue is?

**Comment by sudhanshutiwari264** [comment]
> > OF YOU WANTS TO ADD SOMETHING MORE DO PET ME KNOW !
> > what exactly the issue is?

@maanpatel2492 I have updated the comment It's written from phone previously : )
