### ISSUE TITLE
add feature to dynamically set the attributes.

### ISSUE THREAD

**Issue by Gaurav-Zaiswal** [sudhanshutiwari264/Making-class-in-different-Programming-languages-#45]
Till now the attributes(i.e. price, model, and color) of Vehicle class are set hard-coded. I think it would be better if we make it dynamnic. So that when the program is executed, user can set attributes dynamically.

**Comment by sudhanshutiwari264** [comment]
I know it is good to make it dynamic but we need to stick to permanent attributes for the vehicle class because it  will be easily understandable by the Beginner

**Comment by Gaurav-Zaiswal** [comment]
Then what's your plan for this project. how you what kind of features you are willing to add?

**Comment by sudhanshutiwari264** [comment]
One class attributes are permanent but we can addass many examples as we want in the other examples

**Comment by sudhanshutiwari264** [comment]
But we cann add other folders also for other topics

**Comment by Gaurav-Zaiswal** [comment]
okay, got it ;)
